- name: install apache and php for Debian users
  tags: apache,apache2,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: change timeout setting
  tags: apache,debian,apache2
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ‘^Timeout’
    line: Timeout 500
  when: ansible_distribution == "Debian"
  register: apache2

- name: restart apache2 (Debian)
  tags: apache2
  service:
    name: apache2
    state: restarted
  when: apache2.changed

- name: copy default html file for the site
  tags: apache,apache2,html
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start apache2 web server
  tags: apache,debian,http
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Debian"
