- name: install apache and php for Debian users
  tags: apache,apache2,debian
  package:
    name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest
    update_cache: yes

- name: change timeout setting
  tags: apache,debian,apache2
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ‘^Timeout’
    line: Timeout 700
  when: ansible_distribution == "Debian"
  register: apache2
  notify: restart_apache

- name: copy default html file for the site
  tags: apache,apache2,html
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start apache2 web server
  tags: apache,debian,http
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
